workflows:
  ios-workflow:
    name: iOS Production Build
    environment:
      groups:
        - appstore_credentials # Замените на вашу группу с сертификатами
      xcode: latest
      cocoapods: default
    scripts:
      # Установка минимальной версии iOS
      - name: Set iOS deployment target
        script: |
          # Обновляем Info.plist
          /usr/libexec/PlistBuddy -c "Set :MinimumOSVersion 13.0" ios/Runner/Info.plist
          
          # Обновляем Xcode project settings
          sed -i '' 's/IPHONEOS_DEPLOYMENT_TARGET = [0-9.]*;/IPHONEOS_DEPLOYMENT_TARGET = 13.0;/g' ios/Runner.xcodeproj/project.pbxproj
          
          # Создаем минимальный Podfile если отсутствует
          if [ ! -f "ios/Podfile" ]; then
            echo "platform :ios, '13.0'" > ios/Podfile
            echo "target 'Runner' do" >> ios/Podfile
            echo "  use_frameworks!" >> ios/Podfile
            echo "  use_modular_headers!" >> ios/Podfile
            echo "  pod 'FirebaseFirestore', '~> 10.0'" >> ios/Podfile
            echo "end" >> ios/Podfile
          fi

      # Установка зависимостей
      - name: Install dependencies
        script: |
          flutter pub get
          cd ios
          pod install --repo-update

      # Сборка приложения
      - name: Build IPA
        script: |
          flutter build ipa --release --no-codesign

    artifacts:
      - build/ios/ipa/*.ipa
    publishing:
      app_store_connect:
        auth: integration
        submit_to_testflight: true
      email:
        recipients:
          - your-email@example.com # Замените на ваш email