name: messenger_flutter
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ^3.8.1


dependencies:
  flutter:
    sdk: flutter

    # Firebase
  firebase_core: ^3.15.0
  firebase_auth: ^5.6.2
  cloud_firestore: ^5.6.10

  provider: ^6.1.5

  cupertino_icons: ^1.0.8
  glassmorphism: ^3.0.0
  intl: ^0.20.2
  flutter_slidable: ^4.0.0
  firebase_storage: ^12.4.9
  image_picker: ^1.1.2
  http: ^1.4.0
  html: ^0.15.6
  crypto: ^3.0.6
  photo_view: ^0.15.0
  image: ^4.5.4
  cached_network_image: ^3.4.1
  flutter_launcher_icons: ^0.14.4
  rename: ^3.1.0


dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0


flutter:

  uses-material-design: true

  assets:
    - assets/images/


flutter_launcher_icons:
  android: true
  ios: true
  macos:
    generate: true
  linux:
    generate: true
  web:
    generate: true
  windows:
    generate: true
    icon_size: 256

  image_path: "assets/launcher_icon/icon.png"
  remove_alpha_ios: true