// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAHlzTfCtNfnMwq7ImEXpCu5WyudSX1_r4',
    appId: '1:39801800977:web:8bc8ebe2e7cc65a07624b0',
    messagingSenderId: '39801800977',
    projectId: 'messenger-app-6b103',
    authDomain: 'messenger-app-6b103.firebaseapp.com',
    storageBucket: 'messenger-app-6b103.firebasestorage.app',
    measurementId: 'G-ZM35158R5Q',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAr9UuwE3tvqOvXWm9mewBCUpo8FF2XlWk',
    appId: '1:39801800977:android:4f4ae8441aa6dba17624b0',
    messagingSenderId: '39801800977',
    projectId: 'messenger-app-6b103',
    storageBucket: 'messenger-app-6b103.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD38uqD0p7TrtfDkKZMtFsEAwH6Zh-gBFY',
    appId: '1:39801800977:ios:90ebabf93709f2f87624b0',
    messagingSenderId: '39801800977',
    projectId: 'messenger-app-6b103',
    storageBucket: 'messenger-app-6b103.firebasestorage.app',
    iosBundleId: 'com.example.messengerFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD38uqD0p7TrtfDkKZMtFsEAwH6Zh-gBFY',
    appId: '1:39801800977:ios:90ebabf93709f2f87624b0',
    messagingSenderId: '39801800977',
    projectId: 'messenger-app-6b103',
    storageBucket: 'messenger-app-6b103.firebasestorage.app',
    iosBundleId: 'com.example.messengerFlutter',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAHlzTfCtNfnMwq7ImEXpCu5WyudSX1_r4',
    appId: '1:39801800977:web:3c9be2123ef2c5407624b0',
    messagingSenderId: '39801800977',
    projectId: 'messenger-app-6b103',
    authDomain: 'messenger-app-6b103.firebaseapp.com',
    storageBucket: 'messenger-app-6b103.firebasestorage.app',
    measurementId: 'G-03DS0JGETN',
  );

}